# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: store_scanner_development

test:
  <<: *default
  database: store_scanner_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>